### ISSUE TITLE
Media encoder queue 

### ISSUE THREAD

**Issue by sohrabafard** [satishsampath/frame-server#35]
Hi,
We use frameserver to encode premiere project with ffmpeg, every thing is fine for one premiere project.
But when we use adobe media encoder to make queue projects, there is one issue : 

When ffmpeg finshed his jobs, frameserver still serving first project on media encoder so we write a program with c++ that detect ffmpeg finished his job and kill process of frameserver, so media encoder automatically start rendering of next project and run frameserver but frameserver needs a user to clicked on "Next" button to start serving,

If you insert an option to skip first dialog, we can use frameserver with Adobe media encoder.

**Comment by zhangyubaka** [comment]
Hello?I need a hand here,x264 cannnot transcode signpost avi
