### ISSUE TITLE
High definition content is served in the wrong colorspace on Premiere Pro CS6

### ISSUE THREAD

**Issue by 7Z0t99** [satishsampath/frame-server#38]
When you export high definition content in Premiere Pro CS6 using Debugmode Frameserver 2.14 and choose to export in YUV, the output will have wrong colors, since Premiere (and most other software) assumes that HD content lies in Rec 709 colorspace, but the frameserver always requests Rec 601.

**Comment by albino1** [comment]
Just so you know, this project hasn't had an actual update in about 4 years, so you're unlikely to get a fix any time soon.  Last year I made a bounty to get it working in Premiere CC (see: https://github.com/satishsampath/frame-server/issues/37), and you're welcome to try and do something similar, but I didn't get any takers.  I wish you luck though.

**Comment by satishsampath** [comment]
If someone is able to reproduce this, can you please add steps here?

**Comment by satishsampath** [comment]
Frameserver 4.0 release has this fix, so marking as closed.
From 4.0, Frameserver is now being maintained/developed as trial/commercial software by the folks at www.cumincode.com/frameserver/ .
