### ISSUE TITLE
Not working on Premiere CC 2019

### ISSUE THREAD

**Issue by wangqr** [satishsampath/frame-server#43]
There is no FrameServer export option in the export dialog. When premiere starts, a warning is shown in the "Events" panel: 
```
A low-level exception occurred in: (Exporter)
```

Relevant parts in `Plugin Loading.log`:
```
Loading from root path: C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore

Scanning for the following file types: *.prmp, *.prm, *.dll, *.aex, *.8bf

Begin PluginNameList::AddFolder C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore 15549.8
PluginNameList::AddFilePath - added "C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore\dfscPremiereOutCS5.prm" 15550.2
Finished PluginNameList::AddFolder C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore 15550.2
Scanning C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore and sub-directories

Loading C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore\dfscPremiereOutCS5.prm

The registry tells us not to cache so the plugin will be loaded from disk.

Loading from disk...

This plugin was recognized by loader d3092dcf-904a-4a97-b4ca-66aed7540d57.
```

The plugin was working fine on Pr CC 2018 on the same machine.

**Comment by wangqr** [comment]
I've re-build the plugin with latest Pr plugin SDK. Debugger showed that some exception happened at [PremiereFS.cpp#L58](https://github.com/satishsampath/frame-server/blob/7de109c6e13dbd0a1fb29c918c32d9ddf66491a1/src/PremiereV2/PremiereFS.cpp#L58). I replaced the `debug` function with a dummy one. Now it works fine.

**Comment by wangqr** [comment]
I do have a build that works on my PrPro CC 2019 @ Win10, at https://ftp.wangqr.tk/frame-server/, and source at [wangqr/frame-server](https://github.com/wangqr/frame-server). I haven't tested it on the mentioned issues.

**Comment by javacty** [comment]
I use your modify version .but in premiere cc 2019 v12.0,   when video encoder read virtual avi file,  report  error?

**Comment by wangqr** [comment]
> 
> 
> I use your modify version .but in premiere cc 2019 v12.0, when video encoder read virtual avi file, report error?

What is the encoder you are using and what is the error you see? I'm using the AVI in AviSynth, which should work fine. There are some softwares which are not able to read the AVI directly and you may need to create an AviSynth script to load the AVI, for example `ffmpeg`.

**Comment by dmirandaa** [comment]
> I do have a build that works on my PrPro CC 2019 @ Win10, at https://ftp.wangqr.tk/frame-server/, and source at [wangqr/frame-server](https://github.com/wangqr/frame-server). I haven't tested it on the mentioned issues.
> 
> To use it, install the original 2.14 version without installing any plugin, and put the prm file into `C:\Program Files\Adobe\Adobe Premiere Pro CC 2019\Plug-Ins\Common`

It works fine on CC 2019.

**Comment by satishsampath** [comment]
@dmirandaa  @wangqr  @albino1  I have an installer tested on Win7 64bit with the latest Premiere Elements. Can I request your help in trying it out? I'd like to verify if it works on Premiere Pro and on Windows 10 before releasing. You can email me at 'satish -at- debugmode.com' and I'll send the build/exe for testing.

**Comment by dmirandaa** [comment]
Hi, sorry for the late reply.

Of course I can help you.

Please, let me know how to do it.

**Comment by satishsampath** [comment]
This issue is fixed with the release of Frameserver 3.0 today. Get it at https://www.debugmode.com/frameserver/

**Comment by wbwarshaw** [comment]
Hmm, upgraded to 3.0 and now only exporting Green Frames from Premiere Pro CC 13.1.2 on Windows 10.

**Comment by wbwarshaw** [comment]
Update: DMFS is exporting solid green frames with YUY2 format selected, solid black frames with RGB24 selected.
