### ISSUE TITLE
Still cannot export 2nd time in CS6

### ISSUE THREAD

**Issue by crutchlow87** [satishsampath/frame-server#44]
I have the 2.14 version safely removed and the 3.0 version installed, but it still will not allow me to export a 2nd time in Premiere Pro. The only thing that works is deleting the chunk of the .prproj file which handles the "lastusedpreset". I also have to delete the line after saying <"Seq.IgnoreMarkersAndIngredients"> or it still won't work, 

Note - When I first run the DMFS and click About it _does_ identify itself as 3.0, so I know I'm using the correct version.

**Comment by satishsampath** [comment]
Sorry, I don't have CS6 nor can I find any website where I can download/install CS6. Any chance you can record a video of the issue on your screen and attach a link here?

**Comment by crutchlow87** [comment]
I can't provide a video, but I can tell you very simply - The first time I export a particular project with DMFS, it works as normal. If I then close the file and reopen it later - even if I don't save it - the Media Coder will not even appear when I click Export. No errors appear. The program does not crash. There is simply no response from clicking File > Export. The only way to restore functionality to that particular project file and save as a different format is to delete the tags from the .prproj file as listed above.

**Comment by satishsampath** [comment]
I'm sorry but I have no way of fixing it now. This problem doesn't happen in newer versions of Premiere Pro and I can't get a copy of CS6 to debug the issue, so your workaround is the only option at this point.
