### ISSUE TITLE
Addition of 1 second added to Vegas Pro timeline to fix audio bug in Frameserver

### ISSUE THREAD

**Issue by DrZen33** [satishsampath/frame-server#45]
I am reporting a well known problem with using Frameserver and Vegas Pro.
I mentioned this in your thread on the Vegas Pro Forums here and you asked me to report here on Github.
https://www.vegascreativesoftware.info/us/forum/debugmode-frameserver-3-0-released--116069/#ca721394

When Frameserving directly from the Vegas Pro timeline into Handbrake, there is an audio bug that requires the addition of exactly **1 second of blank space** to be added to the end of the timeline. Doing this keeps the audio and video in sync.

I explain how to temporarily fix this bug in this part of my tutorial on the topic:
https://www.moviestudiozen.com/free-tutorials/sony-vegas-pro/590-render-video-from-vegas-pro-to-handbrake#a7

It would be great to have this bug fixed once and for all, so that you don't have to add 1 second before beginning a render.

Thank you.
Derek (Dr Zen)

p.s.
On a separate audio issue, I would also like to see 48kHz supported instead of only 44.1kHz

**Comment by satishsampath** [comment]
@DrZen33 I'm looking at solving this issue, but noticed that your webpage doesn't give an exact reproduction of the issue. Can I request that you give me a short list of steps to reproduce the issue? For example, if I open a Vegas project that's 40 seconds and directly frameserve to TMPGEnc, I see that the output mpg is exactly 40 seconds. Is that not the case with Handbrake? Giving a simple repro scenario will help me a lot!

**Comment by DrZen33** [comment]
Hi Satish

I have recorded a video screen capture for you, which shows exactly what I have been doing.
https://youtu.be/dNPqHnJbvyc

Here is a copy of my 10 second test video:
https://youtu.be/BiQZCtqgzb4

Here is a copy of my Vegas test project made with Vegas Pro 16.
[vegas-test-project.zip](https://github.com/satishsampath/frame-server/files/3615166/vegas-test-project.zip)

Link to my tutorial/article that lists ALL the apps and scripts I used to make Vegas to Handbrake work.
https://www.moviestudiozen.com/free-tutorials/sony-vegas-pro/590-render-video-from-vegas-pro-to-handbrake

Regards
Derek

**Comment by hclivess** [comment]
Is this a generic problem? I'm using vegas to ffmpeg and have not noticed

**Comment by DevDesignGirl** [comment]
I have same problem, when rendering signpost.avi, created with Debugmode Frameserver, with enabled "write audio as PCM samples in signpost AVI"
Vegas Pro 17.0, rendering like this:
https://i.imgur.com/6JWzC7N.png
https://i.imgur.com/sWPTsqC.png
It does not matter, which render mechanism you use (in my case I'm using A's Video Converter), cause if throw this signpost avi to other copy of vegas, you will able to see this some part of sound at the end of video is "prolongated", some sort of strange dublicate effect. See comparision upper part - original, below - rendered:
https://i.imgur.com/D7K9Wus.png
For long video this effect is getting longer, like, you can hear some phrase for 2-3 secs.

**Comment by Kidsnd274** [comment]
Having the same problem as well but I have a workaround (I don't think it will work with Handbrake though)

I'm using Framserver to serve directly to StaxRip and rendering out the video using the PCM file that Frameserver generates does have that extra second of audio. The workaround that I'm currently using is to export the audio as a FLAC file or PCM WAV file first using Vegas Pro then import that audio file when rendering out with Frameserver. So StaxRip would use the video stream coming from Frameserver and using the audio stream from the exported audio file.

I've edited @DrZen33 's script (thanks a lot, your script is awesome) to render out the audio first as a FLAC file, followed by starting up Frameserver and then launching StaxRip with both files automatically added and ready for rendering.

Hope this workaround helps someone. Adding 1 second of emptiness doesn't always fix any weird sounds at the end.

**Comment by YvanCB** [comment]
Hello,
I have the same problem with "**Vegas Pro 18**" + "**Frameserver 3.1**" + "**StaxRip encoder**".

Examples:
Audio directly send with the Frameserver using the option "Write audio as PCM samples in signpost AVI". :
https://youtu.be/6UGZbSiYBd0

Audio send before (not in the Frameserver) : https://youtu.be/wzYwZ9ogD5Q 

I export the audio sepratly and don't use the option"Write audio as PCM ... AVI".

It's not a big deal but to be perfect is it possible to solve this little bug?

Regards.

**Comment by satishsampath** [comment]
I have a fix that seems to work, so want to ask if anyone would like to test it and confirm whether it works for your needs. If you are interested, please email me directly - satish -at- debugmode .dot. com

**Comment by DrZen33** [comment]
Audio bug has now been fixed in v3.3.1
Works in both Vegas Pro 18 and Vegas Pro 17.

**Comment by satishsampath** [comment]
Frameserver 4.0 release has this fix, so marking as closed.
From 4.0, Frameserver is now being maintained/developed as trial/commercial software by the folks at www.cumincode.com/frameserver/ .
