### ISSUE TITLE
3.0 Not working on Premiere CC 2019 13.1.2

### ISSUE THREAD

**Issue by wbwarshaw** [satishsampath/frame-server#47]
Upgraded to 3.0 and now only exporting solid Green Frames from Premiere Pro CC 13.1.2 on Windows 10 with YUY2 format selected.  Solid Black Frames exported with RGB24 selected.

**Comment by satishsampath** [comment]
Since #46  was closed, can you please confirm if this issue is also closed or do you still have this problem? @wbwarshaw

**Comment by wbwarshaw** [comment]
This issue should be closed as well.  All is working now as expected.
