### ISSUE TITLE
Frameserver 3.0  Premiere 2018  does not work

### ISSUE THREAD

**Issue by videocorr** [satishsampath/frame-server#48]
The frameserver 3.0 does not work in Adode Premiere 2018. Perhaps the reason is that the installer has the wrong dfscPremiereOut.prm file, it looks like this is an old file that was in version 2.14 and was called dfscPremiereOutCS5.prm
video with error:
https://drive.google.com/open?id=1qNaHdLAFspUmTSiuWBtztPPJXEqYep_k

Windows 7 SP1, Premiere 2018.1 (12.1.2 build 69)

**Comment by satishsampath** [comment]
I notice that you have the setting "Write audio as PCM samples in signpost AVI" unchecked (in your video above, it's shown in the frameserver dialog at the 25th second). Can you please enable that and see if that fixes the issue? I'm still debugging.

**Comment by videocorr** [comment]
With option "Write audio as PCM samples in signpost AVI" same error
In this video test for RGB24 and YUY2:
https://drive.google.com/open?id=1DAcXAKUQceHM97lRSjEAb9Ziumv5zhIx

**Comment by satishsampath** [comment]
Can you please email me, satish -at- debugmode -dot- com, so we can continue debugging this faster & I can send you some debug builds to try out?

**Comment by videocorr** [comment]
Ok, email you, my email   videocorr@gmail.com

**Comment by videocorr** [comment]
I found the reason: in the Media Encoder and Premiere Pro folders there are old files from version 2.14 that I copied to these 2 folders:
"c: \ Program Files \ Adobe \ Adobe Media Encoder CC 2018 \ Plug-Ins \ Common \ dfscPremiereOutCS5.prm"
"c: \ Program Files \ Adobe \ Adobe Premiere Pro CC 2018 \ Plug-Ins \ Common \ dfscPremiereOutCS5.prm"

By default, the plugin is placed in the folder "c: \ Program Files \ Adobe \ Common \ Plug-ins \ 7.0 \ MediaCore \ dfscPremiereOut.prm", and the old version of dfscPremiereOutCS5.prm remains in the previous folders

After replacing the old dfscPremiereOutCS5.prm file with the new dfscPremiereOut.prm, everything worked, including in Adobe Media Encoder.
