### ISSUE TITLE
The latest release is 3 years old

### ISSUE THREAD

**Issue by hclivess** [satishsampath/frame-server#49]
I see there has been some work going on, but the latest Windows release is 3 years old. Anyone planning on updating it?

**Comment by satishsampath** [comment]
You are probably looking at the file fssetup-2.1.4.exe, which is the previous release.
The latest release was updated 17 days ago, file "fssetup.exe" - https://github.com/satishsampath/frame-server/blob/master/fssetup.exe

**Comment by hclivess** [comment]
Thanks, can we please make use of https://github.com/satishsampath/frame-server/releases ?

**Comment by satishsampath** [comment]
Yep, I've tagged the latest release as v3.0 per your suggestion. Thanks.
