### ISSUE TITLE
Render Options grayed out in Vegas Pro 17

### ISSUE THREAD

**Issue by Petermgr** [satishsampath/frame-server#51]
I have upgraded from Vegas Pro 15 to 17.  I have used FrameServer 3.0 in Pro 15 with no issues. In Pro 17, while I can still render out using FrameServer, the Render Options is grayed out.  See screenshot.  I have tried uninstalling FrameServer, running CCleaner, doing a reboot, but still the problem persists. The Render Options did work in Pro 15 and from it I could select Render Loop Region Only. 

I also tried uninstalling Vegas Pro 17 and reinstalling with a fresh boot. No luck.

![FrameServer](https://user-images.githubusercontent.com/55855956/65721950-04970880-e060-11e9-823d-88a338a83148.png)

Thanks.

**Comment by DevDesignGirl** [comment]
I also have this problem, maybe its because that for Vegas 17 DMFS does not install in "native" mode like with Vegas 16 and you have to show some folders to it, and it missing something?

**Comment by satishsampath** [comment]
Closing this issue as it has been a while and people have worked around it.
