### ISSUE TITLE
Wave file size limitation -- Add W64 support

### ISSUE THREAD

**Issue by musicvid** [satishsampath/frame-server#52]
Program audio source (aac, ac3) is compressed 5:1 to 10:1 in some cases. When decoding longer (2+ hour) programs to PCM, the legacy .WAV file size limitation is quickly exceeded, making program-length audio frameserving impossible, such as with Happy Otter Scripts.

For Magix / Sony users, adding Wave 64 pipeline support would be an ideal solution, possibly without upsetting the existing infrastructure too much.

**Comment by satishsampath** [comment]
Closing this issue because w64 is a proprietary format, likely only understood by Vegas/SoundForge software and not compatible with AVI format in general.

**Comment by malini-cumincode** [comment]
This issue is now fixed. CuminCode (the new developers of FrameServer) have built a paid version and the latest release of FrameseServer 4.21 has Wave64 capability if you enable the "virtual AVI file" option. Check it out at https://www.cumincode.com/frameserver/ .
