### ISSUE TITLE
ffmpeg codec support

### ISSUE THREAD

**Issue by jet082** [satishsampath/frame-server#57]
To some degree this is not something that you can do directly, but it would be nice to have a patch, or at least some documentation for the DFSC format, which could lead to one being created (and hopefully accepted by the project).

I believe that most of us using ffmpeg are decoding via avisynth, but that adds another step to the process and unnecessary latency, which adds up. It seems to me that it would be possible to add support in ffmpeg for this codec (or to create a patch to do so at a minimum).

https://wiki.multimedia.cx/index.php?title=FFmpeg_codec_HOWTO
https://wiki.multimedia.cx/index.php/FFmpeg_demuxer_HOWTO

The above sites seem relevant for this.

**Comment by satishsampath** [comment]
This sounds like a good idea. I personally don't have the time to implement it, but happy to help anyone with information if they'd like to contribute an ffmpeg patch.

**Comment by jet082** [comment]
Is this something you would be interested in if a bounty was placed on it on bountify? I'd be willing to chip in 100 dollars for that, I think.

If not, I would be interested in being pointed in the direction of some documentation so as to be able to possibly write it myself.

**Comment by malini-cumincode** [comment]
This is now fixed. CuminCode (the new developers of FrameServer) have built a paid version and the latest release of FrameseServer 4.21 works with ffmpeg, TMPGenc and almost every other encoder & NLE. Check it out at https://www.cumincode.com/frameserver/ .

**Comment by malini-cumincode** [comment]
This is now fixed. CuminCode (the new developers of FrameServer) have built a paid version and the latest release of FrameseServer 4.21 works with ffmpeg, TMPGenc and almost every other encoder & NLE. Check it out at https://www.cumincode.com/frameserver/ .
